spring:
  application:
    name: global-config

  profiles:
    active: default

  cloud:
    config:
      allow-override: true
      override-none: false
      override-system-properties: false

eureka:
  instance:
    hostname: config-server
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

logging:
  level:
    root: INFO