spring:
  application:
    name: global-config

  profiles:
    active: default

  cloud:
    config:
      allowOverride: true
      overrideNone: false
      overrideSystemProperties: false

logging:
  level:
    root: INFO