server:
    port: 8080

spring:
    application:
        name: gateway
    cloud:
        gateway:
            server:
                webflux:
                    routes:
                        - id: auth-service
                          uri: lb://auth-service
                          predicates:
                              - Path=/api/v1/auth/**
                        - id: user-service
                          uri: lb://user-service
                          predicates:
                              - Path=/api/v1/users/**
                        - id: quiz-service
                          uri: lb://quiz-service
                          predicates:
                              - Path=/api/v1/quiz/**

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://eureka-server:8761/eureka
    instance:
        prefer-ip-address: true
        hostname: gateway
