server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://auth-service:8081
              predicates:
                - Path=/api/auth/**
            - id: user-service
              uri: http://user-service:8082
              predicates:
                - Path=/api/user/**
            - id: quiz-service
              uri: http://quiz-service:8083
              predicates:
                - Path=/api/quiz/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: gateway