services:
  eureka-server:
    image: eun61n/moneython-eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - moneython-networks
    healthcheck:
      test: ["CMD", "curl", "-f", "http://eureka-server:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  config-server:
    image: eun61n/moneython-config-server:latest
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      - GIT_REPO=https://github.com/eun61n00/moneython
    networks:
      - moneython-networks
    depends_on:
      - eureka-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://config-server:8888/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  auth-service:
    image: eun61n/moneython-auth-service:latest
    container_name: auth-service
    ports:
      - "8081:8081"
    networks:
      - moneython-networks
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  user-service:
    image: eun61n/moneython-user-service:latest
    container_name: user-service
    ports:
      - "8082:8082"
    networks:
      - moneython-networks
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  quiz-service:
    image: eun61n/moneython-quiz-service:latest
    container_name: quiz-service
    ports:
      - "8083:8083"
    networks:
      - moneython-networks
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

  gateway:
    image: eun61n/moneython-gateway:latest
    container_name: gateway
    ports:
      - "8080:8080"
    networks:
      - moneython-networks
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      auth-service:
        condition: service_started
      user-service:
        condition: service_started
      quiz-service:
        condition: service_started

networks:
  moneython-networks:
    driver: bridge
