server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/eun61n00/moneython
          default-label: feat/msa-architecture-setup
          search-paths: backend/config-server/config-repo