name: Deploy Backend to EC2

on:
    push:
        branches: ["main"]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./backend

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to DockerHub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            - name: Build & Push Multi-Service Docker Images
              run: |
                  docker compose -f docker-compose.yml build
                  docker tag moneython-auth-service ${{ secrets.DOCKER_HUB_USERNAME }}/moneython-auth-service:latest
                  docker tag moneython-user-service ${{ secrets.DOCKER_HUB_USERNAME }}/moneython-user-service:latest
                  docker tag moneython-quiz-service ${{ secrets.DOCKER_HUB_USERNAME }}/moneython-quiz-service:latest
                  docker tag moneython-config-server ${{ secrets.DOCKER_HUB_USERNAME }}/moneython-config-server:latest
                  docker tag moneython-eureka-server ${{ secrets.DOCKER_HUB_USERNAME }}/moneython-eureka-server:latest
                  docker tag moneython-gateway ${{ secrets.DOCKER_HUB_USERNAME }}/moneython-gateway:latest

                  docker push ${{ secrets.DOCKER_HUB_USERNAME }}/moneython-auth-service:latest
                  docker push ${{ secrets.DOCKER_HUB_USERNAME }}/moneython-user-service:latest
                  docker push ${{ secrets.DOCKER_HUB_USERNAME }}/moneython-quiz-service:latest
                  docker push ${{ secrets.DOCKER_HUB_USERNAME }}/moneython-config-server:latest
                  docker push ${{ secrets.DOCKER_HUB_USERNAME }}/moneython-eureka-server:latest
                  docker push ${{ secrets.DOCKER_HUB_USERNAME }}/moneython-gateway:latest

            - name: Copy docker-compose.yml to EC2
              uses: appleboy/scp-action@v0.1.4
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_KEY }}
                  source: "backend/docker-compose.ec2.yml"
                  target: "/home/ubuntu/moneython"

            - name: Deploy to EC2
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_KEY }}
                  script: |
                      cd /home/ubuntu/moneython/backend
                      echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
                      docker-compose down
                      docker-compose pull
                      docker-compose up -d --remove-orphans
