name: Deploy Backend to EC2

on:
    push:
        branches: ["main"]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./backend

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            # - name: Run tests
            #   run: |
            #     ./gradlew :auth-service:test -Dspring.profiles.active=test
            #     ./gradlew :user-service:test -Dspring.profiles.active=test
            #     ./gradlew :quiz-service:test -Dspring.profiles.active=test
            #     ./gradlew :gateway:test -Dspring.profiles.active=test
            #     ./gradlew :config-server:test -Dspring.profiles.active=test

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to DockerHub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            - name: Build and Push Docker Images
              run: |
                  # docker-compose.yml에 DOCKER_USER 변수를 전달하여 이미지 이름을 동적으로 설정
                  # Git Commit SHA를 이미지 태그로 사용
                  export GIT_TAG=${{ github.sha }}
                  export DOCKER_USER=${{ secrets.DOCKER_HUB_USERNAME }}
                  docker compose -f docker-compose.yml build
                  docker compose -f docker-compose.yml push

            - name: Write SSH key
              run: |
                  echo "${{ secrets.EC2_KEY }}" > key.pem
                  chmod 600 key.pem

            - name: Copy docker-compose.prod.yml to EC2
              run: |
                  scp -i key.pem -o StrictHostKeyChecking=no docker-compose.prod.yml ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ubuntu/moneython/

            - name: Deploy to EC2
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_KEY }}
                  script: |
                      cd /home/ubuntu/moneython
                      export GIT_TAG=${{ github.sha }}
                      export DOCKER_USER=${{ secrets.DOCKER_HUB_USERNAME }}
                      echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
                      # docker-compose.prod.yml을 사용하여 배포
                      docker compose -f docker-compose.prod.yml down
                      docker compose -f docker-compose.prod.yml pull
                      docker compose -f docker-compose.prod.yml up -d --remove-orphans
