name: Deploy Backend to EC2

on:
    push:
        branches: ["main"]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./backend

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to DockerHub
              uses: docker-login-action@v3
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            - name: Build & Push Multi-Service Docker Images
              run: |
                  docker-compose -f docker-compose.yml build
                  docker tag auth-service ${{ secrets.DOCKER_HUB_USERNAME }}/auth-service:latest
                  docker tag user-service ${{ secrets.DOCKER_HUB_USERNAME }}/user-service:latest
                  docker tag quiz-service ${{ secrets.DOCKER_HUB_USERNAME }}/quiz-service:latest
                  docker tag config-server ${{ secrets.DOCKER_HUB_USERNAME }}/config-server:latest
                  docker tag eureka-server ${{ secrets.DOCKER_HUB_USERNAME }}/eureka-server:latest
                  docker tag gateway ${{ secrets.DOCKER_HUB_USERNAME }}/gateway:latest

                  docker push ${{ secrets.DOCKER_HUB_USERNAME }}/auth-service:latest
                  docker push ${{ secrets.DOCKER_HUB_USERNAME }}/user-service:latest
                  docker push ${{ secrets.DOCKER_HUB_USERNAME }}/quiz-service:latest
                  docker push ${{ secrets.DOCKER_HUB_USERNAME }}/config-server:latest
                  docker push ${{ secrets.DOCKER_HUB_USERNAME }}/eureka-server:latest
                  docker push ${{ secrets.DOCKER_HUB_USERNAME }}/gateway:latest

            - name: Deploy to EC2
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_KEY }}
                  script: |
                      cd /home/ubuntu/moneython
                      git pull origin main
                      docker-compose down
                      docker-compose pull
                      docker-compose up -d --remove-orphans

                        # docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/moneython-backend
                        # docker stop moneython || true
                        # docker rm moneython || true
                        # docker run -d --name moneython -p 8080:8080 ${{ secrets.DOCKER_HUB_USERNAME }}/moneython-backend
